# Diagnoses imbalanced

In [1]:
import numpy as np
import pandas as pd

In [2]:
#pd.set_option("display.max_rows", None)

In [3]:
df = pd.read_csv("data/diagnoosit.csv")
df_fi = pd.read_csv("data/FI_diagnoosit.csv")

In [4]:
df_fi.shape

(75058, 10)

In [4]:
#df.value_counts("diagnoosi")

In [15]:
df.value_counts("ikaryhma")

ikaryhma
55-59    143277
60-64    138353
50-54    131941
45-49    127238
40-44    122288
35-39    111457
30-34    102106
25-29     84970
20-24     64246
65-67     41981
16-19     25898
Name: count, dtype: int64

In [5]:
df_16_19 = df[df["ikaryhma"]=="20-24"]
df_16_19.value_counts("diagnoosi")

diagnoosi
F41 Muut ahdistuneisuushäiriöt                                                  367
F32 Masennustila                                                                358
F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt                            342
M54 Selkäsärky                                                                  338
F33 Toistuva masennus                                                           329
                                                                               ...
J05 Akuutti ahtauttava kurkunpäätulehdus (kruppi) ja/tai kurkunkansitulehdus      4
C18 Koolonin syöpä                                                                4
E85 Amyloidoosi                                                                   2
S11 Kaulan haava                                                                  2
T30 Sijainniltaan määrittämättömät palovammat ja syöpymät                         2
Name: count, Length: 831, dtype: int64

In [6]:
df.head(20)

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,alkanut_kausi_lkm,ka_paiva_lkm,ka_maksettu/paiva
0,Vuosikertymä,7,2025,30-34,Nainen,Yhteensä,D15 Muiden ja määrittämättömien rintaontelon e...,1,45.00,68.97
1,Vuosikertymä,11,2024,30-34,Mies,Yhteensä,R33 Virtsaumpi,1,15.00,74.53
2,Vuosikertymä,2,2025,45-49,Nainen,Sairauspäiväraha,E03 Muu kilpirauhasen vajaatoiminta,1,15.00,71.43
3,Vuosikertymä,11,2025,30-34,Mies,Sairauspäiväraha,F64 Sukupuoli-identiteetin häiriöt,15,13.37,58.64
4,Vuosikertymä,3,2025,45-49,Mies,Sairauspäiväraha,S53 Kyynärnivelen seudun nivelten tai siteiden...,4,22.25,68.71
5,Vuosikertymä,6,2024,50-54,Nainen,Sairauspäiväraha,G12 Spinaalinen lihasatrofia ja lähisukuiset o...,6,69.62,64.22
6,Kuukausi,4,2025,20-24,Nainen,Sairauspäiväraha,L05 Pilonidaalikysta,2,8.50,51.22
7,Vuosikertymä,9,2025,25-29,Mies,Yhteensä,T29 Useiden kehonosien palovammat ja syöpymät,1,23.00,41.29
8,Vuosikertymä,10,2025,65-67,Nainen,YEL-päiväraha,S42 Hartianseudun tai olkavarren murtuma,1,9.00,54.75
9,Vuosikertymä,3,2024,55-59,Mies,YEL-päiväraha,R06 Hengityksen poikkeavuudet,1,9.00,123.63
10,Vuosikertymä,10,2025,65-67,Nainen,Yhteensä,G56 Yläraajan yhden hermon sairaudet,47,27.49,66.42
11,Vuosikertymä,7,2025,55-59,Mies,Yhteensä,"Z63 Muut primaarisen tukiryhmän ongelmat, perh...",1,3.00,75.85
12,Vuosikertymä,4,2025,16-19,Nainen,Sairauspäiväraha,J03 Akuutti nielurisatulehdus,7,2.71,40.11
13,Kuukausi,10,2025,30-34,Nainen,Yhteensä,Q79 Muualla luokittamattomat synnynnäiset liha...,1,21.00,56.02
14,Vuosikertymä,3,2025,45-49,Mies,Yhteensä,J34 Muut nenäontelon ja nenän sivuonteloiden s...,9,4.12,66.19
15,Kuukausi,7,2024,45-49,Mies,Sairauspäiväraha,"Z00 Yleistarkastus joka kohdistuu henkilöihin,...",0,11.00,82.10
16,Vuosikertymä,11,2025,45-49,Mies,Yhteensä,F43 Reaktiot vaikeaan stressiin ja sopeutumish...,524,26.83,62.76
17,Vuosikertymä,10,2025,55-59,Mies,Yhteensä,I28 Muut keuhkoverisuonien sairaudet,0,32.00,98.70
18,Vuosikertymä,10,2024,60-64,Nainen,Yhteensä,L89 Makuuhaava,0,36.00,44.83
19,Kuukausi,3,2025,40-44,Mies,Yhteensä,L90 Ihon surkastumasairaudet,1,1.00,790.35

In [7]:
df_ = df[df["diagnoosi"]=="E11 Aikuistyypin diabetes"]
df_.value_counts("ikaryhma")

ikaryhma
55-59    297
60-64    292
50-54    283
45-49    240
40-44    218
35-39    193
30-34    120
65-67     98
25-29     74
20-24     60
Name: count, dtype: int64

In [8]:
df1 = df[df["diagnoosi"].isin(["M16 Lonkan nivelrikko", "C77 Syövän etäpesäke (sekundaarinen syöpä) tai määrittämätön pahanlaatuinen kasvain imusolmukkeessa", "C16 Mahasyöpä", "K25 Mahalaukun haava", "I21 Sydäninfarkti", "A46 Ruusu", "E11 Aikuistyypin diabetes"])]

In [9]:
df1.shape

(13232, 10)

In [10]:
df1.value_counts("diagnoosi")

diagnoosi
M16 Lonkan nivelrikko                                                                                  3058
A46 Ruusu                                                                                              2432
I21 Sydäninfarkti                                                                                      2405
E11 Aikuistyypin diabetes                                                                              1875
C16 Mahasyöpä                                                                                          1366
C77 Syövän etäpesäke (sekundaarinen syöpä) tai määrittämätön pahanlaatuinen kasvain imusolmukkeessa    1190
K25 Mahalaukun haava                                                                                    906
Name: count, dtype: int64

In [11]:
df_fi.value_counts("ikaryhma")

ikaryhma
55-59    7679
40-44    7664
50-54    7654
45-49    7654
35-39    7579
60-64    7563
30-34    7371
25-29    7089
20-24    6148
65-67    4705
16-19    3952
Name: count, dtype: int64

In [12]:
df.value_counts("ikaryhma")

ikaryhma
55-59    143277
60-64    138353
50-54    131941
45-49    127238
40-44    122288
35-39    111457
30-34    102106
25-29     84970
20-24     64246
65-67     41981
16-19     25898
Name: count, dtype: int64

In [13]:
df1.value_counts("ikaryhma")

ikaryhma
60-64    2008
55-59    1895
50-54    1819
45-49    1618
40-44    1497
35-39    1277
65-67    1061
30-34     961
25-29     634
20-24     356
16-19     106
Name: count, dtype: int64

In [14]:
df1 = df1[df1["ikaryhma"].isin(["60-64", "65-67", "30-34", "25-29", "20-24", "16-19"])]
df1.shape

(5126, 10)

In [38]:
df_20000 = df.iloc[:20000]

In [39]:
df_20000.value_counts("ikaryhma")

ikaryhma
55-59    2666
60-64    2488
50-54    2358
45-49    2282
40-44    2273
35-39    2027
30-34    1873
25-29    1586
20-24    1198
65-67     765
16-19     484
Name: count, dtype: int64

In [40]:
df_vaihtoehtoinen = df_20000[df_20000["ikaryhma"].isin(["55-59","20-24", "25-29", "65-67"])]
df_vaihtoehtoinen.shape

(6215, 10)

In [41]:
df_vaihtoehtoinen.value_counts("ikaryhma")

ikaryhma
55-59    2666
25-29    1586
20-24    1198
65-67     765
Name: count, dtype: int64

In [42]:
df1 = df_vaihtoehtoinen

In [43]:
df1.to_csv("data/clf_imbalanced_diagnoosit.csv", index=False)

In [15]:
df.value_counts("ka_paiva_lkm")

ka_paiva_lkm
9.00      55661
25.00     39487
6.00      26123
2.00      26041
3.00      25337
          ...
0.33          1
87.49         1
1.17          1
255.33        1
2.08          1
Name: count, Length: 12120, dtype: int64

In [16]:
df = df.replace("-", None)
df["ka_paiva_lkm"]=df["ka_paiva_lkm"].astype(float)

In [17]:
df2 = df[((df["ka_paiva_lkm"] >= 1 ) & (df["ka_paiva_lkm"] <= 40)) | (df["ka_paiva_lkm"] >= 200)]

In [18]:
df2.value_counts("ka_paiva_lkm")

ka_paiva_lkm
9.00      55661
25.00     39487
6.00      26123
2.00      26041
3.00      25337
          ...
300.00        1
2.07          1
2.05          1
2.09          1
2.08          1
Name: count, Length: 3958, dtype: int64

In [19]:
df2.shape

(861032, 10)

In [20]:
df2.head(20)

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,alkanut_kausi_lkm,ka_paiva_lkm,ka_maksettu/paiva
1,Vuosikertymä,11,2024,30-34,Mies,Yhteensä,R33 Virtsaumpi,1,15.00,74.53
2,Vuosikertymä,2,2025,45-49,Nainen,Sairauspäiväraha,E03 Muu kilpirauhasen vajaatoiminta,1,15.00,71.43
3,Vuosikertymä,11,2025,30-34,Mies,Sairauspäiväraha,F64 Sukupuoli-identiteetin häiriöt,15,13.37,58.64
4,Vuosikertymä,3,2025,45-49,Mies,Sairauspäiväraha,S53 Kyynärnivelen seudun nivelten tai siteiden...,4,22.25,68.71
6,Kuukausi,4,2025,20-24,Nainen,Sairauspäiväraha,L05 Pilonidaalikysta,2,8.50,51.22
7,Vuosikertymä,9,2025,25-29,Mies,Yhteensä,T29 Useiden kehonosien palovammat ja syöpymät,1,23.00,41.29
8,Vuosikertymä,10,2025,65-67,Nainen,YEL-päiväraha,S42 Hartianseudun tai olkavarren murtuma,1,9.00,54.75
9,Vuosikertymä,3,2024,55-59,Mies,YEL-päiväraha,R06 Hengityksen poikkeavuudet,1,9.00,123.63
10,Vuosikertymä,10,2025,65-67,Nainen,Yhteensä,G56 Yläraajan yhden hermon sairaudet,47,27.49,66.42
11,Vuosikertymä,7,2025,55-59,Mies,Yhteensä,"Z63 Muut primaarisen tukiryhmän ongelmat, perh...",1,3.00,75.85
12,Vuosikertymä,4,2025,16-19,Nainen,Sairauspäiväraha,J03 Akuutti nielurisatulehdus,7,2.71,40.11
13,Kuukausi,10,2025,30-34,Nainen,Yhteensä,Q79 Muualla luokittamattomat synnynnäiset liha...,1,21.00,56.02
14,Vuosikertymä,3,2025,45-49,Mies,Yhteensä,J34 Muut nenäontelon ja nenän sivuonteloiden s...,9,4.12,66.19
15,Kuukausi,7,2024,45-49,Mies,Sairauspäiväraha,"Z00 Yleistarkastus joka kohdistuu henkilöihin,...",0,11.00,82.10
16,Vuosikertymä,11,2025,45-49,Mies,Yhteensä,F43 Reaktiot vaikeaan stressiin ja sopeutumish...,524,26.83,62.76
17,Vuosikertymä,10,2025,55-59,Mies,Yhteensä,I28 Muut keuhkoverisuonien sairaudet,0,32.00,98.70
18,Vuosikertymä,10,2024,60-64,Nainen,Yhteensä,L89 Makuuhaava,0,36.00,44.83
19,Kuukausi,3,2025,40-44,Mies,Yhteensä,L90 Ihon surkastumasairaudet,1,1.00,790.35
22,Kuukausi,4,2025,40-44,Mies,Yhteensä,R07 Kurkkukipu ja rintakipu,1,1.00,79.07
23,Vuosikertymä,11,2024,65-67,Mies,Sairauspäiväraha,S86 Polven ja/tai säären alueen lihas- ja/tai ...,8,29.67,76.74

In [21]:
df2 = df2.iloc[:10000]

In [22]:
df2.value_counts("ka_paiva_lkm")

ka_paiva_lkm
9.0      648
25.0     498
6.0      295
3.0      294
2.0      294
        ...
236.0      1
232.5      1
226.0      1
218.0      1
216.5      1
Name: count, Length: 1652, dtype: int64

In [23]:
df2.to_csv("data/reg_imbalanced_diagnoosit.csv", index=False)