# Diagnoosit pseudo words

In [1]:
import numpy as np
import pandas as pd
import random
import string

In [2]:
df =  pd.read_csv("data/FI_diagnoosit.csv")
df_original = df

In [2]:
def pseudo_words(length, list_length):
    words=[]
    for i in range(list_length):
        word = ''.join(random.choices(string.ascii_lowercase, k=length))
        word = word.capitalize()
        words.append(word)

    return (words)

In [4]:
words=(pseudo_words(10, 41))
print(words)

['Bmgsvsyyfq', 'Zrgtpmdfzm', 'Mpanrqkikk', 'Kloqcrfuej', 'Kmwitxjcvy', 'Niilsxeehw', 'Pvqelpxkbz', 'Skvcsalhgm', 'Izabgxcodc', 'Nczsnfyarm', 'Xjjtyuxuof', 'Zctnozvezo', 'Djieavegwv', 'Owudzmigcw', 'Qkghyrmrjw', 'Uqvrktozuy', 'Ibludjahrd', 'Pvhtiyshyy', 'Tzaibgjhfg', 'Qdfjwhyosh', 'Gbrpyuvylt', 'Vgbdmroesc', 'Ixoxxdgxtm', 'Pjqabdcfdx', 'Vshthzlvfp', 'Scaqmoruir', 'Pjpjzgeisk', 'Asgacuxdqa', 'Zyvgqnsvbh', 'Cnchgzkpnd', 'Jlvojqkwjx', 'Wutrqptrfd', 'Gvaaypvvzu', 'Jndkemimas', 'Cgodcppckt', 'Ipfdzgkwvl', 'Fjkurykqyl', 'Yumwijftno', 'Ikievshrdu', 'Mapaursxuz', 'Xrpeqvuway']

In [5]:
df = df.rename(columns={"aikatyyppi": words[0] , "kuukausi_nro": words[1], "vuosi": words[2], "ikaryhma": words[3], "sukupuoli": words[4], "etuus":words[5], "diagnoosi":words[6], "alkanut_kausi_lkm":words[7], "ka_paiva_lkm":words[8], "ka_maksettu/paiva":words[9]})

In [6]:
df = df.replace("Vuosikertymä", words[10])
df = df.replace("Kuukausi", words[11])
df = df.replace("Nainen", words[12])
df = df.replace("Mies", words[13])
df = df.replace("F41 Muut ahdistuneisuushäiriöt", words[14])
df = df.replace("M54 Selkäsärky", words[15])
df = df.replace("F32 Masennustila", words[16])
df = df.replace("F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt", words[17])
df = df.replace("F33 Toistuva masennus", words[18])
df = df.replace("F51 Ei-elimelliset unihäiriöt", words[19])
df = df.replace("M51 Muut selän nikamavälilevyjen sairaudet", words[20])
df = df.replace("M79 Muualla luokittamattomat muut pehmytkudossairaudet", words[21])
df = df.replace("S83 Polven alueen nivelten ja siteiden sijoiltaanmeno, nyrjähdys ja/tai venähdys", words[22])
df = df.replace("S82 Polven ja/tai säären murtuma", words[23])
df = df.replace("G56 Yläraajan yhden hermon sairaudet", words[24])
df = df.replace("M75 Hartianseudun pehmytkudossairaudet", words[25])
df = df.replace("M25 Muualla luokittamattomat muut nivelsairaudet", words[26])
df = df.replace("S52 Kyynärvarren murtuma", words[27])
df = df.replace("S92 Jalkaterän luiden murtumat", words[28])
df = df.replace("M77 Muut siteiden ja lihasjänteiden kiinnittymiskohtien sairaudet (entesopatiat)", words[29])
df = df.replace("S43 Hartianseudun (hartiakaaren) nivelten ja siteiden sijoiltaanmeno, nyrjähdys ja/tai venähdys", words[30])
df = df.replace("F31 Kaksisuuntainen mielialahäiriö", words[31])
df = df.replace("J06 Useissa tai määrittämättömissä ylähengitysteiden kohdissa esiintyvä akuutti infektio", words[32])
df = df.replace("S62 Ranteen tai käden murtuma", words[33])
df = df.replace("M23 Polven sisäiset viat", words[34])
df = df.replace("Sairauspäiväraha", words[35])
df = df.replace("Yhteensä", words[36])
df = df.replace("Osasairauspäiväraha", words[37])
df = df.replace("YEL-päiväraha", words[38])
df = df.replace("Tartuntatautipäiväraha", words[39])
df = df.replace("Luovutuspäiväraha", words[40])

In [7]:
df.head(10)

,Bmgsvsyyfq,Zrgtpmdfzm,Mpanrqkikk,Kloqcrfuej,Kmwitxjcvy,Niilsxeehw,Pvqelpxkbz,Skvcsalhgm,Izabgxcodc,Nczsnfyarm
0,Xjjtyuxuof,10,2025,65-67,Djieavegwv,Fjkurykqyl,Vshthzlvfp,47,27.49,66.42
1,Xjjtyuxuof,11,2025,45-49,Owudzmigcw,Fjkurykqyl,Pvhtiyshyy,524,26.83,62.76
2,Xjjtyuxuof,11,2025,60-64,Owudzmigcw,Yumwijftno,Scaqmoruir,52,63.22,38.75
3,Xjjtyuxuof,9,2025,45-49,Djieavegwv,Ikievshrdu,Wutrqptrfd,2,4.50,90.16
4,Xjjtyuxuof,8,2025,65-67,Djieavegwv,Ipfdzgkwvl,Pjpjzgeisk,19,27.95,50.08
5,Zctnozvezo,11,2025,40-44,Owudzmigcw,Yumwijftno,Zyvgqnsvbh,1,24.50,35.90
6,Xjjtyuxuof,1,2025,35-39,Djieavegwv,Fjkurykqyl,Asgacuxdqa,22,19.71,59.54
7,Zctnozvezo,10,2024,60-64,Owudzmigcw,Yumwijftno,Tzaibgjhfg,1,24.25,40.29
8,Xjjtyuxuof,6,2024,20-24,Djieavegwv,Ipfdzgkwvl,Jlvojqkwjx,20,23.22,46.97
9,Zctnozvezo,4,2025,40-44,Djieavegwv,Fjkurykqyl,Scaqmoruir,39,19.22,57.53

In [8]:
df_original.head(10)

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,alkanut_kausi_lkm,ka_paiva_lkm,ka_maksettu/paiva
0,Vuosikertymä,10,2025,65-67,Nainen,Yhteensä,G56 Yläraajan yhden hermon sairaudet,47,27.49,66.42
1,Vuosikertymä,11,2025,45-49,Mies,Yhteensä,F43 Reaktiot vaikeaan stressiin ja sopeutumish...,524,26.83,62.76
2,Vuosikertymä,11,2025,60-64,Mies,Osasairauspäiväraha,M75 Hartianseudun pehmytkudossairaudet,52,63.22,38.75
3,Vuosikertymä,9,2025,45-49,Nainen,YEL-päiväraha,F31 Kaksisuuntainen mielialahäiriö,2,4.50,90.16
4,Vuosikertymä,8,2025,65-67,Nainen,Sairauspäiväraha,M25 Muualla luokittamattomat muut nivelsairaudet,19,27.95,50.08
5,Kuukausi,11,2025,40-44,Mies,Osasairauspäiväraha,S92 Jalkaterän luiden murtumat,1,24.50,35.90
6,Vuosikertymä,1,2025,35-39,Nainen,Yhteensä,S52 Kyynärvarren murtuma,22,19.71,59.54
7,Kuukausi,10,2024,60-64,Mies,Osasairauspäiväraha,F33 Toistuva masennus,1,24.25,40.29
8,Vuosikertymä,6,2024,20-24,Nainen,Sairauspäiväraha,S43 Hartianseudun (hartiakaaren) nivelten ja s...,20,23.22,46.97
9,Kuukausi,4,2025,40-44,Nainen,Yhteensä,M75 Hartianseudun pehmytkudossairaudet,39,19.22,57.53

In [9]:
df.to_csv("data/pseudo_diagnoosit.csv", index=False)

# Bikes pesudo words

In [14]:
EN_Bikes = pd.read_csv("data/EN_Bikes.csv")

In [15]:
EN_Bikes = EN_Bikes[EN_Bikes["Return station name"].isin(["Töölönlahdenkatu", "Itämerentori", "Kamppi (M)", "Ympyrätalo"])]
EN_Bikes = EN_Bikes[EN_Bikes["Departure station name"].isin(["Töölönlahdenkatu", "Itämerentori", "Tyynenmerenkatu", "Salmisaarenranta", "Baana", "Kamppi (M)", "Ympyrätalo"])]

In [16]:
EN_Bikes.head()

,Departure station id,Departure station name,Return station id,Return station name,Covered distance (m),Duration (sec.),Year,Month,Departure day,Departure hour,Departure min.,Departure sec.,Return day,Return hour,Return min.,Return sec.
15,21,Töölönlahdenkatu,30.0,Itämerentori,1988.0,547,2019.0,7.0,31.0,10.0,20.0,20.0,31.0,10.0,29.0,32.0
48,21,Töölönlahdenkatu,30.0,Itämerentori,1909.0,472,2019.0,6.0,6.0,16.0,16.0,26.0,6.0,16.0,24.0,23.0
62,30,Itämerentori,21.0,Töölönlahdenkatu,1931.0,470,2019.0,5.0,7.0,16.0,18.0,7.0,7.0,16.0,26.0,1.0
101,41,Ympyrätalo,21.0,Töölönlahdenkatu,1946.0,545,2019.0,5.0,17.0,9.0,16.0,15.0,17.0,9.0,25.0,29.0
153,21,Töölönlahdenkatu,21.0,Töölönlahdenkatu,610.0,218,2019.0,6.0,11.0,15.0,18.0,38.0,11.0,15.0,22.0,17.0

In [17]:
EN_Bikes.shape

(43385, 16)

In [18]:
words=(pseudo_words(10, 24))
print(words)

['Dkkkycxpjh', 'Ajjmckzlbg', 'Tqszqoscyj', 'Uobpawxhpf', 'Oambjpgszp', 'Ptaflkyvmh', 'Fwbbrjgyau', 'Bdxtsmtulo', 'Onpsewdfrl', 'Oqodehmuyz', 'Ezcmboagcw', 'Subpyffejp', 'Zcxfbwpslo', 'Pmrdjzwzlz', 'Kwstocaanq', 'Qyaropmaie', 'Cykkezgfbk', 'Svupnkpbji', 'Dppomvpmbi', 'Ctdxdxtxtq', 'Imzkkmshqs', 'Besloafbic', 'Ofizsblyha', 'Wmbqdexdwd']

In [19]:
EN_Bikes = EN_Bikes.rename(columns={"Departure station id": words[0] , "Departure station name": words[1], "Return station id": words[2], "Return station name": words[3], "Covered distance (m)": words[4], "Duration (sec.)":words[5], "Year":words[6], "Month":words[7], "Departure day":words[8], "Departure hour":words[9], "Departure min.":words[10], "Departure sec.":words[11], "Return day":words[12], "Return hour":words[13], "Return min.":words[14], "Return sec.":words[15]})

In [20]:
EN_Bikes.head()

,Dkkkycxpjh,Ajjmckzlbg,Tqszqoscyj,Uobpawxhpf,Oambjpgszp,Ptaflkyvmh,Fwbbrjgyau,Bdxtsmtulo,Onpsewdfrl,Oqodehmuyz,Ezcmboagcw,Subpyffejp,Zcxfbwpslo,Pmrdjzwzlz,Kwstocaanq,Qyaropmaie
15,21,Töölönlahdenkatu,30.0,Itämerentori,1988.0,547,2019.0,7.0,31.0,10.0,20.0,20.0,31.0,10.0,29.0,32.0
48,21,Töölönlahdenkatu,30.0,Itämerentori,1909.0,472,2019.0,6.0,6.0,16.0,16.0,26.0,6.0,16.0,24.0,23.0
62,30,Itämerentori,21.0,Töölönlahdenkatu,1931.0,470,2019.0,5.0,7.0,16.0,18.0,7.0,7.0,16.0,26.0,1.0
101,41,Ympyrätalo,21.0,Töölönlahdenkatu,1946.0,545,2019.0,5.0,17.0,9.0,16.0,15.0,17.0,9.0,25.0,29.0
153,21,Töölönlahdenkatu,21.0,Töölönlahdenkatu,610.0,218,2019.0,6.0,11.0,15.0,18.0,38.0,11.0,15.0,22.0,17.0

In [21]:
EN_Bikes = EN_Bikes.replace("Töölönlahdenkatu", words[16])
EN_Bikes = EN_Bikes.replace("Itämerentori", words[17])
EN_Bikes = EN_Bikes.replace("Kamppi (M)", words[18])
EN_Bikes = EN_Bikes.replace("Ympyrätalo", words[19])
EN_Bikes = EN_Bikes.replace("Tyynenmerenkatu", words[20])
EN_Bikes = EN_Bikes.replace("Salmisaarenranta", words[21])
EN_Bikes = EN_Bikes.replace("Baana", words[22])

In [22]:
EN_Bikes.head()

,Dkkkycxpjh,Ajjmckzlbg,Tqszqoscyj,Uobpawxhpf,Oambjpgszp,Ptaflkyvmh,Fwbbrjgyau,Bdxtsmtulo,Onpsewdfrl,Oqodehmuyz,Ezcmboagcw,Subpyffejp,Zcxfbwpslo,Pmrdjzwzlz,Kwstocaanq,Qyaropmaie
15,21,Cykkezgfbk,30.0,Svupnkpbji,1988.0,547,2019.0,7.0,31.0,10.0,20.0,20.0,31.0,10.0,29.0,32.0
48,21,Cykkezgfbk,30.0,Svupnkpbji,1909.0,472,2019.0,6.0,6.0,16.0,16.0,26.0,6.0,16.0,24.0,23.0
62,30,Svupnkpbji,21.0,Cykkezgfbk,1931.0,470,2019.0,5.0,7.0,16.0,18.0,7.0,7.0,16.0,26.0,1.0
101,41,Ctdxdxtxtq,21.0,Cykkezgfbk,1946.0,545,2019.0,5.0,17.0,9.0,16.0,15.0,17.0,9.0,25.0,29.0
153,21,Cykkezgfbk,21.0,Cykkezgfbk,610.0,218,2019.0,6.0,11.0,15.0,18.0,38.0,11.0,15.0,22.0,17.0

In [23]:
pseudo_Bikes = EN_Bikes

In [24]:
pseudo_Bikes.value_counts("Ajjmckzlbg")

Ajjmckzlbg
Cykkezgfbk    8684
Svupnkpbji    7376
Imzkkmshqs    7356
Besloafbic    6799
Ofizsblyha    6418
Ctdxdxtxtq    3377
Dppomvpmbi    3375
Name: count, dtype: int64

In [25]:
pseudo_Bikes.value_counts("Uobpawxhpf")

Uobpawxhpf
Svupnkpbji    18475
Cykkezgfbk    15287
Dppomvpmbi     5343
Ctdxdxtxtq     4280
Name: count, dtype: int64

In [26]:
pseudo_Bikes.to_csv("data/pseudo_bikes.csv", index=False)

# Weather pesudo words

In [28]:
FI_kumpula = pd.read_csv("data/FI_kumpula_19-25.csv")

In [29]:
FI_kumpula.value_counts("Vallitseva sää")

Vallitseva sää
Heikkoa lumisadetta                                                                     3037
Heikkoa vesisadetta                                                                     2210
Utua                                                                                    1948
Heikkoja vesikuuroja                                                                    1515
Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä     809
Heikkoa tai kohtalaista sadetta                                                          788
Heikkoja lumikuuroja                                                                     531
Name: count, dtype: int64

In [30]:
FI_kumpula.head()

,Vuosi,Kuukausi,Päivä,Näkyvyys keskiarvo (m),Ilman lämpötila keskiarvo (°C),Pilvisyys (1/8),Suhteellinen kosteus keskiarvo (%),Vallitseva sää,Tuulen suunta keskiarvo (°),Keskituulen nopeus keskiarvo (m/s),Tunti (Paikallinen aika)
0,2021,12,3,16200,-8.6,7,84.3,Heikkoa lumisadetta,214.8,3.6,17
1,2023,2,8,2175,1.9,8,100.0,Utua,225.6,6.8,21
2,2022,2,24,25527,-0.6,8,93.4,Heikkoja lumikuuroja,213.8,7.2,0
3,2019,1,11,5586,0.8,8,95.7,Heikkoa lumisadetta,243.9,9.1,6
4,2022,12,23,3331,0.8,8,98.9,Heikkoa lumisadetta,324,6.2,19

In [ ]:
words=(pseudo_words(10, 50))
print(words)

In [32]:
FI_kumpula = FI_kumpula.rename(columns={"Vuosi": words[0] , "Kuukausi": words[1], "Päivä": words[2], "Näkyvyys keskiarvo (m)": words[3], "Ilman lämpötila keskiarvo (°C)": words[4], "Pilvisyys (1/8)":words[5], "Suhteellinen kosteus keskiarvo (%)":words[6], "Vallitseva sää":words[7], "Tuulen suunta keskiarvo (°)":words[8], "Keskituulen nopeus keskiarvo (m/s)":words[9], "Tunti (Paikallinen aika)":words[10]})

In [33]:
FI_kumpula.head()

,Dkkkycxpjh,Ajjmckzlbg,Tqszqoscyj,Uobpawxhpf,Oambjpgszp,Ptaflkyvmh,Fwbbrjgyau,Bdxtsmtulo,Onpsewdfrl,Oqodehmuyz,Ezcmboagcw
0,2021,12,3,16200,-8.6,7,84.3,Heikkoa lumisadetta,214.8,3.6,17
1,2023,2,8,2175,1.9,8,100.0,Utua,225.6,6.8,21
2,2022,2,24,25527,-0.6,8,93.4,Heikkoja lumikuuroja,213.8,7.2,0
3,2019,1,11,5586,0.8,8,95.7,Heikkoa lumisadetta,243.9,9.1,6
4,2022,12,23,3331,0.8,8,98.9,Heikkoa lumisadetta,324,6.2,19

In [34]:
FI_kumpula = FI_kumpula.replace("Heikkoa lumisadetta", words[11])
FI_kumpula = FI_kumpula.replace("Heikkoa vesisadetta", words[12])
FI_kumpula = FI_kumpula.replace("Utua", words[13])
FI_kumpula = FI_kumpula.replace("Heikkoja vesikuuroja", words[14])
FI_kumpula = FI_kumpula.replace("Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä", words[15])
FI_kumpula = FI_kumpula.replace("Heikkoa tai kohtalaista sadetta", words[16])
FI_kumpula = FI_kumpula.replace("Heikkoja lumikuuroja", words[17])

In [35]:
FI_kumpula.value_counts("Bdxtsmtulo")

Bdxtsmtulo
Subpyffejp    3037
Zcxfbwpslo    2210
Pmrdjzwzlz    1948
Kwstocaanq    1515
Qyaropmaie     809
Cykkezgfbk     788
Svupnkpbji     531
Name: count, dtype: int64

In [36]:
pseudo_weather=FI_kumpula

In [37]:
pseudo_weather.to_csv("data/pseudo_weather.csv", index=False)