In [1]:
import numpy as np
import pandas as pd

In [2]:
#pd.set_option("display.max_rows", None)

In [3]:
df = pd.read_csv("data/diagnoosit.csv")

In [4]:
df.shape

(1093755, 10)

In [5]:
df.head()

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,alkanut_kausi_lkm,ka_paiva_lkm,ka_maksettu/paiva
0,Vuosikertymä,7,2025,30-34,Nainen,Yhteensä,D15 Muiden ja määrittämättömien rintaontelon e...,1,45.00,68.97
1,Vuosikertymä,11,2024,30-34,Mies,Yhteensä,R33 Virtsaumpi,1,15.00,74.53
2,Vuosikertymä,2,2025,45-49,Nainen,Sairauspäiväraha,E03 Muu kilpirauhasen vajaatoiminta,1,15.00,71.43
3,Vuosikertymä,11,2025,30-34,Mies,Sairauspäiväraha,F64 Sukupuoli-identiteetin häiriöt,15,13.37,58.64
4,Vuosikertymä,3,2025,45-49,Mies,Sairauspäiväraha,S53 Kyynärnivelen seudun nivelten tai siteiden...,4,22.25,68.71

In [6]:
print(df["aikatyyppi"].unique())

['Vuosikertymä' 'Kuukausi']

In [7]:
print(df["sukupuoli"].unique())

['Nainen' 'Mies']

In [8]:
print(df["etuus"].unique())

['Yhteensä' 'Sairauspäiväraha' 'YEL-päiväraha' 'Osasairauspäiväraha'
 'Tartuntatautipäiväraha' 'Luovutuspäiväraha']

In [9]:
print(df["diagnoosi"].unique())

['D15 Muiden ja määrittämättömien rintaontelon elinten hyvänlaatuiset kasvaimet'
 'R33 Virtsaumpi' 'E03 Muu kilpirauhasen vajaatoiminta' ...
 'E76 Glykosaminoglykaanien aineenvaihduntahäiriöt'
 'R54 Seniliteetti (vanhusmaisuus)' 'L65 Muu arpea muodostamaton hiuskato']

In [10]:
df.value_counts("diagnoosi")

diagnoosi
F41 Muut ahdistuneisuushäiriöt                          3948
M54 Selkäsärky                                          3907
F32 Masennustila                                        3906
F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt    3859
F33 Toistuva masennus                                   3737
                                                        ...
T68 Hypotermia                                             4
E40 Vaikea proteiinialiravitsemus                          4
Q69 Monisormisuus ja/tai monivarpaisuus                    4
A35 Muu jäykkäkouristus                                    4
Z08 Pahanlaatuisen kasvaimen hoidon jälkitarkastus         4
Name: count, Length: 1430, dtype: int64

In [11]:
df = df[df["diagnoosi"].isin(["F41 Muut ahdistuneisuushäiriöt", "M54 Selkäsärky", "F32 Masennustila", "F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt", "F33 Toistuva masennus", "F51 Ei-elimelliset unihäiriöt", "M51 Muut selän nikamavälilevyjen sairaudet", "M79 Muualla luokittamattomat muut pehmytkudossairaudet", "S83 Polven alueen nivelten ja siteiden sijoiltaanmeno, nyrjähdys ja/tai venähdys", "S82 Polven ja/tai säären murtuma", "G56 Yläraajan yhden hermon sairaudet", "M75 Hartianseudun pehmytkudossairaudet", "M25 Muualla luokittamattomat muut nivelsairaudet", "S52 Kyynärvarren murtuma", "S92 Jalkaterän luiden murtumat", "M77 Muut siteiden ja lihasjänteiden kiinnittymiskohtien sairaudet (entesopatiat)", "S43 Hartianseudun (hartiakaaren) nivelten ja siteiden sijoiltaanmeno, nyrjähdys ja/tai venähdys", "F31 Kaksisuuntainen mielialahäiriö", "J06 Useissa tai määrittämättömissä ylähengitysteiden kohdissa esiintyvä akuutti infektio", "S62 Ranteen tai käden murtuma", "M23 Polven sisäiset viat"])]

In [12]:
df.shape

(75058, 10)

In [14]:
df.to_csv("data/FI_diagnoosit.csv", index=False)

In [15]:
df = df.rename(columns={"aikatyyppi": "time_category" , "kuukausi_nro": "month_number", "vuosi": "year", "ikaryhma": "age_group", "sukupuoli": "sex", "etuus":"benefit_type", "diagnoosi":"diagnosis", "alkanut_kausi_lkm":"benefit_periods_started", "ka_paiva_lkm":"average_number_of_days", "ka_maksettu/paiva":"average_amount_paid/day"})

In [16]:
df.head()

,time_category,month_number,year,age_group,sex,benefit_type,diagnosis,benefit_periods_started,average_number_of_days,average_amount_paid/day
10,Vuosikertymä,10,2025,65-67,Nainen,Yhteensä,G56 Yläraajan yhden hermon sairaudet,47,27.49,66.42
16,Vuosikertymä,11,2025,45-49,Mies,Yhteensä,F43 Reaktiot vaikeaan stressiin ja sopeutumish...,524,26.83,62.76
20,Vuosikertymä,11,2025,60-64,Mies,Osasairauspäiväraha,M75 Hartianseudun pehmytkudossairaudet,52,63.22,38.75
50,Vuosikertymä,9,2025,45-49,Nainen,YEL-päiväraha,F31 Kaksisuuntainen mielialahäiriö,2,4.50,90.16
53,Vuosikertymä,8,2025,65-67,Nainen,Sairauspäiväraha,M25 Muualla luokittamattomat muut nivelsairaudet,19,27.95,50.08

In [17]:
df = df.replace("Vuosikertymä", "Annual cumulative total")
df = df.replace("Kuukausi", "Month")
df = df.replace("Nainen", "Female")
df = df.replace("Mies", "Male")
df = df.replace("F41 Muut ahdistuneisuushäiriöt", "F41 Other anxiety disorders")
df = df.replace("M54 Selkäsärky", "M54 Dorsalgia")
df = df.replace("F32 Masennustila", "F32 Depressive episode")
df = df.replace("F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt", "F43 Reaction to severe stress, and adjustment disorders")
df = df.replace("F33 Toistuva masennus", "F33 Recurrent depressive disorder")
df = df.replace("F51 Ei-elimelliset unihäiriöt", "F51 Nonorganic sleep disorders")
df = df.replace("M51 Muut selän nikamavälilevyjen sairaudet", "M51 Other intervertebral disc disorders")
df = df.replace("M79 Muualla luokittamattomat muut pehmytkudossairaudet", "M79 Other soft tissue disorders, not elsewhere classified")
df = df.replace("S83 Polven alueen nivelten ja siteiden sijoiltaanmeno, nyrjähdys ja/tai venähdys", "S83 Dislocation, sprain and strain of joints and ligaments of knee")
df = df.replace("S82 Polven ja/tai säären murtuma", "S82 Fracture of lower leg, including ankle")
df = df.replace("G56 Yläraajan yhden hermon sairaudet", "G56 Mononeuropathies of upper limb")
df = df.replace("M75 Hartianseudun pehmytkudossairaudet", "M75 Shoulder lesions")
df = df.replace("M25 Muualla luokittamattomat muut nivelsairaudet", "M25 Other joint disorders, not elsewhere classified")
df = df.replace("S52 Kyynärvarren murtuma", "S52 Fracture of forearm")
df = df.replace("S92 Jalkaterän luiden murtumat", "S92 Fracture of foot, except ankle")
df = df.replace("M77 Muut siteiden ja lihasjänteiden kiinnittymiskohtien sairaudet (entesopatiat)", "M77 Other enthesopathies")
df = df.replace("S43 Hartianseudun (hartiakaaren) nivelten ja siteiden sijoiltaanmeno, nyrjähdys ja/tai venähdys", "S43 Dislocation, sprain and strain of joints and ligaments of shoulder girdle")
df = df.replace("F31 Kaksisuuntainen mielialahäiriö", "F31 Bipolar affective disorder")
df = df.replace("J06 Useissa tai määrittämättömissä ylähengitysteiden kohdissa esiintyvä akuutti infektio", "J06 Acute upper respiratory infections of multiple and unspecified sites")
df = df.replace("S62 Ranteen tai käden murtuma", "S62 Fracture at wrist and hand level")
df = df.replace("M23 Polven sisäiset viat", "M23 Internal derangement of knee")
df = df.replace("Sairauspäiväraha", "Sickness allowance")
df = df.replace("Yhteensä", "Total")
df = df.replace("Osasairauspäiväraha", "Partial sicness allowance")
df = df.replace("YEL-päiväraha", "Self-employed person's sickness allowance")
df = df.replace("Tartuntatautipäiväraha", "Infectious desease allowance")
df = df.replace("Luovutuspäiväraha", "Donation allowance")

In [19]:
df.head()

,time_category,month_number,year,age_group,sex,benefit_type,diagnosis,benefit_periods_started,average_number_of_days,average_amount_paid/day
10,Annual cumulative total,10,2025,65-67,Female,Total,G56 Mononeuropathies of upper limb,47,27.49,66.42
16,Annual cumulative total,11,2025,45-49,Male,Total,"F43 Reaction to severe stress, and adjustment ...",524,26.83,62.76
20,Annual cumulative total,11,2025,60-64,Male,Partial sicness allowance,M75 Shoulder lesions,52,63.22,38.75
50,Annual cumulative total,9,2025,45-49,Female,Self-employed person's sickness allowance,F31 Bipolar affective disorder,2,4.50,90.16
53,Annual cumulative total,8,2025,65-67,Female,Sickness allowance,"M25 Other joint disorders, not elsewhere class...",19,27.95,50.08

In [20]:
df.to_csv("data/EN_diagnoosit.csv", index=False)