In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/EN_Bikes.csv")

In [3]:
df.head()

,Departure station id,Departure station name,Return station id,Return station name,Covered distance (m),Duration (sec.),Year,Month,Departure day,Departure hour,Departure min.,Departure sec.,Return day,Return hour,Return min.,Return sec.
0,56,Luoteisväylä,541.0,"Aalto-yliopisto (M), Korkeakouluaukio",3683.0,712,2019.0,6.0,19.0,8.0,49.0,15.0,19.0,9.0,1.0,8.0
1,135,Velodrominrinne,148.0,Juhana Herttuan tie,2726.0,727,2019.0,7.0,24.0,21.0,58.0,40.0,24.0,22.0,10.0,51.0
2,727,Ratsutori,711.0,Kirjurinkuja,1025.0,292,2019.0,5.0,14.0,16.0,18.0,11.0,14.0,16.0,23.0,2.0
3,711,Kirjurinkuja,729.0,Leppävaaranaukio,946.0,278,2019.0,5.0,31.0,20.0,47.0,53.0,31.0,20.0,52.0,32.0
4,43,Karhupuisto,16.0,Liisanpuistikko,1451.0,517,2019.0,7.0,1.0,16.0,38.0,39.0,1.0,16.0,47.0,21.0

In [4]:
df = df.rename(columns={"Departure station id": "Lähtöaseman id" , "Return station id": "Palautusaseman id", "Departure station name": "Lähtöaseman nimi", "Return station name": "Palautusaseman nimi", "Covered distance (m)": "Kuljettu matka (m)", "Duration (sec.)": "Kesto (sek.)", "Year": "Vuosi", "Month": "Kuukausi", "Departure day": "Lähtöpäivä", "Departure hour":"Lähtö tunti", "Departure min.": "Lähtö min.", "Departure sec.":"Lähtö sek.", "Return day": "Palautuspäivä", "Return hour":"Palautus tunti", "Return hour": "Palautustunti", "Return min.": "Palautus min.", "Return sec.": "Palautus sek."})

In [5]:
df.head()

,Lähtöaseman id,Lähtöaseman nimi,Palautusaseman id,Palautusaseman nimi,Kuljettu matka (m),Kesto (sek.),Vuosi,Kuukausi,Lähtöpäivä,Lähtö tunti,Lähtö min.,Lähtö sek.,Palautuspäivä,Palautustunti,Palautus min.,Palautus sek.
0,56,Luoteisväylä,541.0,"Aalto-yliopisto (M), Korkeakouluaukio",3683.0,712,2019.0,6.0,19.0,8.0,49.0,15.0,19.0,9.0,1.0,8.0
1,135,Velodrominrinne,148.0,Juhana Herttuan tie,2726.0,727,2019.0,7.0,24.0,21.0,58.0,40.0,24.0,22.0,10.0,51.0
2,727,Ratsutori,711.0,Kirjurinkuja,1025.0,292,2019.0,5.0,14.0,16.0,18.0,11.0,14.0,16.0,23.0,2.0
3,711,Kirjurinkuja,729.0,Leppävaaranaukio,946.0,278,2019.0,5.0,31.0,20.0,47.0,53.0,31.0,20.0,52.0,32.0
4,43,Karhupuisto,16.0,Liisanpuistikko,1451.0,517,2019.0,7.0,1.0,16.0,38.0,39.0,1.0,16.0,47.0,21.0

In [6]:
df.to_csv("data/FI_Bikes.csv", index=False)