In [1]:
import numpy as np
import pandas as pd

In [2]:
#df = pd.read_csv("data/malmi.csv")
df = pd.read_csv("data/FI_kumpula_19-25.csv")
df.head()

,Vuosi,Kuukausi,Päivä,Näkyvyys keskiarvo (m),Ilman lämpötila keskiarvo (°C),Pilvisyys (1/8),Suhteellinen kosteus keskiarvo (%),Vallitseva sää,Tuulen suunta keskiarvo (°),Keskituulen nopeus keskiarvo (m/s),Tunti (Paikallinen aika)
0,2021,12,3,16200,-8.6,7,84.3,Heikkoa lumisadetta,214.8,3.6,17
1,2023,2,8,2175,1.9,8,100.0,Utua,225.6,6.8,21
2,2022,2,24,25527,-0.6,8,93.4,Heikkoja lumikuuroja,213.8,7.2,0
3,2019,1,11,5586,0.8,8,95.7,Heikkoa lumisadetta,243.9,9.1,6
4,2022,12,23,3331,0.8,8,98.9,Heikkoa lumisadetta,324,6.2,19

In [3]:
df = df.rename(columns={"Vuosi": "Year" , "Tunti (Paikallinen aika)":"Hour (Local time)", "Kuukausi": "Month", "Päivä": "Day", "Ilman lämpötila keskiarvo (°C)": "Average air temperature (°C)", "Pilvisyys (1/8)": "Cloudiness (1/8)", "Näkyvyys keskiarvo (m)": "Average visibility (m)", "Suhteellinen kosteus keskiarvo (%)": "Relative humidity average (%)", "Keskituulen nopeus keskiarvo (m/s)": "Average wind speed (m/s)", "Vallitseva sää": "Current weather", "Tuulen suunta keskiarvo (°)": "Average wind direction (°)"})
df.head()

,Year,Month,Day,Average visibility (m),Average air temperature (°C),Cloudiness (1/8),Relative humidity average (%),Current weather,Average wind direction (°),Average wind speed (m/s),Hour (Local time)
0,2021,12,3,16200,-8.6,7,84.3,Heikkoa lumisadetta,214.8,3.6,17
1,2023,2,8,2175,1.9,8,100.0,Utua,225.6,6.8,21
2,2022,2,24,25527,-0.6,8,93.4,Heikkoja lumikuuroja,213.8,7.2,0
3,2019,1,11,5586,0.8,8,95.7,Heikkoa lumisadetta,243.9,9.1,6
4,2022,12,23,3331,0.8,8,98.9,Heikkoa lumisadetta,324,6.2,19

In [4]:
df.value_counts("Current weather")

Current weather
Heikkoa lumisadetta                                                                     3037
Heikkoa vesisadetta                                                                     2210
Utua                                                                                    1948
Heikkoja vesikuuroja                                                                    1515
Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä     809
Heikkoa tai kohtalaista sadetta                                                          788
Heikkoja lumikuuroja                                                                     531
Name: count, dtype: int64

In [5]:
df.shape

(10838, 11)

In [6]:
df = df.replace("Heikkoa lumisadetta", "Light snow")
df = df.replace("Heikkoa vesisadetta", "Light rain")
df = df.replace("Utua", "Mist")
df = df.replace("Heikkoja vesikuuroja", "Light rain showers")
df = df.replace("Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä", "Drizzle or snow grains during the preceding hour, but not at the time of observation")
df = df.replace("Heikkoa tai kohtalaista sadetta", "Light or moderate precipitation")
df = df.replace("Heikkoja lumikuuroja", "Light snow showers")

In [7]:
df.head()

,Year,Month,Day,Average visibility (m),Average air temperature (°C),Cloudiness (1/8),Relative humidity average (%),Current weather,Average wind direction (°),Average wind speed (m/s),Hour (Local time)
0,2021,12,3,16200,-8.6,7,84.3,Light snow,214.8,3.6,17
1,2023,2,8,2175,1.9,8,100.0,Mist,225.6,6.8,21
2,2022,2,24,25527,-0.6,8,93.4,Light snow showers,213.8,7.2,0
3,2019,1,11,5586,0.8,8,95.7,Light snow,243.9,9.1,6
4,2022,12,23,3331,0.8,8,98.9,Light snow,324,6.2,19

In [8]:
df.to_csv("data/EN_kumpula_19-25.csv", index=False)